"""initial_schema

Revision ID: 550b8eac852b
Revises:
Create Date: 2026-04-18 13:56:19.782676

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "550b8eac852b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("commander_name", sa.String(length=64), nullable=True),
        sa.Column("ship_type", sa.String(length=64), nullable=True),
        sa.Column("journal_filename", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "journal_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("raw_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_journal_events_event_type"),
        "journal_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_journal_events_session_id"),
        "journal_events",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_journal_events_timestamp"),
        "journal_events",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_journal_events_timestamp"), table_name="journal_events")
    op.drop_index(op.f("ix_journal_events_session_id"), table_name="journal_events")
    op.drop_index(op.f("ix_journal_events_event_type"), table_name="journal_events")
    op.drop_table("journal_events")
    op.drop_table("sessions")
    # ### end Alembic commands ###
